spring:
  application:
    name: SwiftRoute

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
#    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swiftroute
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    password: ${DB_PASSWORD}a6e8fe676b49
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 5000
      ssl:
        enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG


jwt:
  secret-key: ${JWT_SECRET}
  access-expiration-ms: 900000  # 15 minutes
  refresh-expiration-ms: 604800000  # 7 days

        #-----------Docker configuration-------------
#spring:
#  application:
#    name: SwiftRoute
#
#  datasource:
#    url: jdbc:mysql://mysql:3306/swiftroute?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#
#server:
#  port: 8080
